version: '3.8'

services:
  # api: Greenlight Go API service
  api:
    build: "." # build from Dockerfile
    ports:
      - "5000"
    restart: "always"
    networks:
      - "api.network"
    depends_on:
      - "db"

  # db: PostgreSQL server
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # init scripts to configure postgres
      - ./remote/docker/db_scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=greenlight
    networks:
      - "api.network"

  db_migrations:
    image: migrate/migrate
    command: -path=/migrations/ -database postgres://postgres:hello@db:5432/greenlight?sslmode=disable up
    restart: "always"
    networks:
      - "api.network"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db

  # nginx: The reverse proxy
  nginx:
    image: nginx:latest
    restart: "always"
    # connect the conf in the container to our config
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - "api.network"

networks:
  api.network: